### ISSUE TITLE
Empty page served

### ISSUE THREAD

**Issue by berezovskyi** [jiemakel/aether#4]
I am running the site with the following commands (gulp ugliness due to #3):

```
npm install
bower install
./node_modules/.bin/gulp --require LiveScript serve
```

I also changed all `^` declarations to `~` for deps to make sure closest versions are used.

The page is empty, but all the css/js resources in the HTML are resolvable. The console contains the following error:

`Unknown provider: $modalProvider <- $modal`.

I would be very grateful for your help!

**Comment by berezovskyi** [comment]
Just stumbled across this solution: http://stackoverflow.com/questions/18733680/unknown-provider-modalprovider-modal-error-with-angularjs

Will submit a PR shorty.

**Comment by jiemakel** [comment]
I'm hesitant to fix this with the PR, as also many of the ui-bootsrap components have had their component names changed to match, and they would need to be hunted down from the jade partials, too - so version pinning it is here again.
